#Import required libraries
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio

pio.templates.default = "plotly_white"

#Read the dataset
data = pd.read_csv("../data/customer_acquisition_data.csv")
print(data.head())

#Exploratory Data Analysis

#Distribution of Acquisition cost
fig = px.histogram(data, x = "cost", nbins = 20,
                   labels={"cost": "Acquisition cost"}, title = "Distribution of Acquisition cost")

fig.show()

fig.write_image("../output/distribution_of_acquisition_cost.png")

#Distribution of Revenue
fig = px.histogram(data, x = "revenue", nbins = 20,
                   labels={"revenue": "Revenue"}, title = "Distribution of Revenue")

fig.show()

fig.write_image("../output/distribution_of_revenue.png")

#COMMENT: From both the distribution plots, we can observe that for 75% of customers, the customer acquisition cost (CAC) is under 10 units while for the remaining customers, the CAC was over 30 units.
# The revenue range 3500-3999 has the highest number of occurrences (110) suggesting most common revenue range and the range 500-999 and 4000-4499 have the lowest number of occurrences (72).
# The revenue ranges with higher frequencies (e.g., 1000-1499, 3500-3999) suggest that revenue is distributed somewhat centered around these ranges. However, there is no clear peak in the middle range.
# To increase revenue, the middle revenue ranges should be focused as those are more common and can help target marketing and sales strategies effectively.
# The lower and higher extremes might be areas to explore further to understand why they are less frequent.

#Most and Least profitable channels
cost_by_channel = data.groupby('channel')['cost'].mean().reset_index()

fig = px.bar(cost_by_channel,
            x = "channel",
            y = "cost",
            title = "Customer Acquisition Cost by Channel",
            labels = {"cost": "Acquisition cost", "channel": "Channel"})

fig.show()

fig.write_image("../output/customer_acquistion_cost_by_channel.png")

#COMMENT: Email Marketing has the lowest CAC at 5.25 (the most cost-effective channel for acquiring customers).
# Paid Advertising has the highest CAC at 30.45 (the most expensive channel for acquiring customers).
# If the organization's goal is to minimize CAC, more budget should be allocated to email marketing.
# However, if the budget is not a problem, strategies should be reassesed to reduce the high CAC for paid advertising.
# Because the email marketing is driving significant customer acquisition at a low cost, it could be a key area to expand.
# Evaluate Referral and Social Media channels to assess their performance and determine if their CAC can be reduced or if they offer any other strategic benefits.

#Most and Least effective channel at converting customers
conversion_by_channel = data.groupby('channel')['conversion_rate'].mean().reset_index()

fig = px.bar(conversion_by_channel,
            x = "channel",
            y = "conversion_rate",
            title = "Conversion Rate by Channel",
            labels = {"conversion_rate": "Conversion rate", "channel": "Channel"})

fig.show()

fig.write_image("../output/conversion_rate_by_channel.png")

#COMMENT: Highest to Lowest conversion rates channels are:
# Social Media (16.76%) > Referral (12.31%) > Email Marketing (4.38%) >Paid Advertising (1.63%)
# While the conversion rate for email marketing might be lower than referral and social media conversion rate, it is still moderately effective in the overall marketing strategy.
# The lowest conversion rate for Paid Advertising indicates that although it may attract a large number of leads, only few of these convert into customers.
# It is beneficial to invest more in referral programs and social media campaigns to further improve conversion rates.
# The conversion rate of email marketing can be improved by personalized content, better segmentation, and targeted campaigns.
# There is a need to reassess paid advertising strategy to improve its effectiveness.

#Revenue generated by Channel
revenue_by_channel = data.groupby('channel')['revenue'].sum().reset_index()

fig = px.bar(revenue_by_channel,
            x = "channel",
            y = "revenue",
            title = "Revenue by Channel",
            labels = {"revenue": "Revenue", "channel": "Channel"})

fig.show()

fig.write_image("../output/revenue_by_channel.png")

fig = px.pie(revenue_by_channel,
            names = "channel",
            values = "revenue",
            title = "Total Revenue by Channel",
            hole = 0.6, color_discrete_sequence=px.colors.qualitative.Pastel)

fig.show()

fig.write_image("../output/total_revenue_by_channel.png")

#COMMENT: Revenue generated and its efficieny is as follows:
# Email Marketing generates the highest revenue at $604.706k, indicating it is the most effective channel in terms of revenue generation. Given its low CAC and reasonable conversion rate, it likely provides a strong return on investment (ROI).
# Referral also shows strong revenue generation of $569.552k which aligns with its high conversion rate. It indicates that referred customers not only convert at a higher rate but also contribute significantly to revenue.
# Paid Advertising generates $548.396k, making it a significant revenue contributor despite its high CAC and low conversion rate. This justifies its higher CAC as the revenue outweighs the acquisition costs.
# Social Media generates the lowest revenue at $492.667k, despite having the highest conversion rate indicating that while it is effective at converting leads, the average transaction value might be lower compared to other channels.

#ROI by Channel
data['roi'] = data['revenue'] / data['cost']

roi_by_channel = data.groupby('channel')['roi'].mean().reset_index()

fig = px.bar(roi_by_channel,
             x = "channel",
             y = "roi",
             title = "Return on Investment (ROI) by Channel",
             labels = {"roi": "Return on Investment", "channel": "Channel"})

fig.show()

fig.write_image("../output/roi_by_channel.png")

#COMMENT: ROI analysis per channel:
# Email marketing generates 538.62 times the cost incurred, indicating it is highly cost-effective and profitable suggesting that email marketing yields substantial revenue for every dollar spent, making it an excellent investment for the business.
# Paid advertising generates 92.83 times the cost incurred, which is the lowest among the channels, however still indicates positive returns based on its high CAC and lower conversion rate, the ROI suggests there is room for optimization to increase its cost-effectiveness.
# Referral marketing generates 330.69 times the cost incurred, indicating it is a very profitable channel because of the high conversion rate, suggesting that referrals are an efficient means of customer acquisition.
# Social media generates 278.96 times the cost incurred, which is a significant profit. Despite generating the least revenue, the high conversion rate helps in maintaining a strong ROI which is indicative of effective cost utilization in this channel.

#Customer Lifetime Value by Channel

data['cltv'] = (data['revenue'] - data['cost']) * (data['conversion_rate'] / data['cost'])

cltv_by_channel = data.groupby('channel')['cltv'].mean().reset_index()

fig = px.bar(cltv_by_channel,
             x = "channel",
             y = "cltv",
             title = "Customer Lifetime Value by Channel",
             labels = {"cltv": "Customer Lifetime Value", "channel": "Channel"})

fig.show()

fig.write_image("../output/cltv_by_channel.png")

#COMMENT: Customer lifetime value by channel:
# CLTV is a ratio that considers how effectively costs are turned into revenue over time.
# The CLTV indicates that for every dollar spent, email marketing generates approximately $23.56 in customer lifetime value which tells us that email marketing is a cost-effective channel with a good balance of revenue generation and conversion rate.
# For every dollar spent, paid advertising generates approximately $1.50 in customer lifetime value which tells us paid advertising is less efficient in converting costs into long-term value. There is a need for optimization in this channel.
# Referral marketing generates approximately $40.60 in customer lifetime value for every dollar spent which reflects the strong performance of referrals in terms of converting costs into substantial long-term value.
# Social media generates approximately $46.58 in customer lifetime value for every dollar spent which is the highest CLTV among all channels. This tell us that social media is extremely efficient in converting marketing spend into long-term customer value.

#CLTV distribution

subset = data.loc[data['channel'].isin(['social media', 'referral'])]

print(subset)

fig = px.box(subset,
             x = "channel",
             y = "cltv",
             title = "CLTV Distribution by Channel",
             labels = {"channel": "Channel", "cltv": "CLTV"})

fig.update_xaxes(title='Channel')
fig.update_yaxes(title='CLTV')
fig.update_layout(legend_title='Channel')

fig.show()

fig.write_image("../output/cltv_distribution_analysis.png")

#COMMENT: CLTV distribution for the higher CLTV generating channels:
# The box plot analysis reveals that while both referral and social media channels are effective in generating high CLTV, social media has the potential to generate higher extreme values of CLTV.
# This variability might stem from the diverse nature of social media campaigns and audiences, leading to a mix of highly valuable and moderately valuable customers.